updated

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -222,29 +222,29 @@ jobs:
             docker ps
 
 # TEST APPLICATION
-      - run :
-          name: Verify if app is reachable using http
-          command: |
-            PORT=8080
-            RETRY_COUNT=0
+      # - run :
+      #     name: Verify if app is reachable using http
+      #     command: |
+      #       PORT=8080
+      #       RETRY_COUNT=0
 
-            while true; do
-                curl http://localhost:$PORT
-                if [ $? -eq 0 ]; then
-                    echo "App is reachable"
-                    break
-                else
-                    RETRY_COUNT=$((RETRY_COUNT+1))
-                    if [ $RETRY_COUNT -eq 3 ]; then
-                        echo "App is not reachable after $RETRY_COUNT retries. Exiting with error."
-                        exit 1
-                    else
-                        echo "App is not reachable. Waiting 5 seconds before trying again..."
-                        sleep 5
-                    fi
-                fi
-            done
-            cat .env
+      #       while true; do
+      #           curl http://localhost:$PORT
+      #           if [ $? -eq 0 ]; then
+      #               echo "App is reachable"
+      #               break
+      #           else
+      #               RETRY_COUNT=$((RETRY_COUNT+1))
+      #               if [ $RETRY_COUNT -eq 3 ]; then
+      #                   echo "App is not reachable after $RETRY_COUNT retries. Exiting with error."
+      #                   exit 1
+      #               else
+      #                   echo "App is not reachable. Waiting 5 seconds before trying again..."
+      #                   sleep 5
+      #               fi
+      #           fi
+      #       done
+      #       cat .env
 
 # PUSH APPLICATION TO DOCKER REGISTRY
       - run:
@@ -422,18 +422,26 @@ jobs:
 workflows:
   wordpress-workflow:
     jobs:
-      - syntax_validation
-      - deploy_vpc_stack:
-          requires: [syntax_validation]
-      - deploy_rds_stack:
-          requires: [deploy_vpc_stack]
-      - get_rds_endpoint:
-          requires: [deploy_rds_stack]
-      - deploy_eks_stack:
-          requires: [deploy_vpc_stack]
+      # - syntax_validation
+      # - deploy_vpc_stack:
+      #     requires: [syntax_validation]
+      # - deploy_rds_stack:
+      #     requires: [deploy_vpc_stack]
+      # - get_rds_endpoint:
+      #     requires: [deploy_rds_stack]
+      # - deploy_eks_stack:
+      #     requires: [deploy_vpc_stack]
+      # - build_app:
+      #     requires: [get_rds_endpoint]      
+      # - deploy_app:
+      #     requires: [deploy_eks_stack, build_app]
+      # - check_health_status:
+      #     requires: [deploy_app]
+
+      - get_rds_endpoint
       - build_app:
           requires: [get_rds_endpoint]      
       - deploy_app:
-          requires: [deploy_eks_stack, build_app]
+          requires: [build_app]
       - check_health_status:
           requires: [deploy_app]
